import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { runResearchRunner } from '../dist/index.js';

const VALIDATION_OK = {
  valid: true,
  summary: { errors: 0, warnings: 0 },
  issues: [],
};

function makeIndicatorDraft({ warmupPeriod, rangeStart, rangeEnd }) {
  // Mirrors the known-good draft shape from research-runner.test.mjs (which
  // passes SDK preflight), with an extra indicator node so the runner can
  // detect a 200-bar lookback and bump warmup deterministically.
  return {
    name: 'Indicator-aware test draft',
    description: 'Generated by research-runner-normalization.test.mjs.',
    signalGraph: {
      protocol: 'traseq.signal-graph',
      version: 2,
      nodes: [
        { id: 'entry_signal', kind: 'pattern', name: 'inside_bar' },
        {
          id: 'sma200',
          kind: 'indicator',
          indicator: 'sma',
          args: { length: 200 },
        },
      ],
      strategy: {
        kind: 'strategy',
        entry: {
          kind: 'entry',
          trigger: { ref: 'entry_signal' },
          action: {
            side: 'long',
            sizing: { mode: 'percent_equity', value: 10 },
          },
        },
      },
    },
    settings:
      warmupPeriod !== undefined
        ? { positionStyle: 'single', warmupPeriod }
        : { positionStyle: 'single' },
    backtest: {
      timeframe: '4h',
      signalInstrument: { symbol: 'BTCUSDT' },
      initialBalance: 10_000,
      ...(rangeStart !== undefined || rangeEnd !== undefined
        ? {
            range: {
              ...(rangeStart !== undefined ? { start: rangeStart } : {}),
              ...(rangeEnd !== undefined ? { end: rangeEnd } : {}),
            },
          }
        : {}),
    },
  };
}

function makeClient() {
  const calls = [];
  return {
    calls,
    async getManifest() {
      return { name: 'Traseq Agent API', version: 'v1' };
    },
    async getWorkspaceContext() {
      return { workspace: { id: 'workspace-1' } };
    },
    async getUsage() {
      return { usage: {}, limits: {} };
    },
    async getCapabilities() {
      return {
        protocol: 'traseq.capabilities',
        version: 1,
        signalGraph: { version: 2, nodes: [], bindings: [] },
        indicators: [],
        operators: { compare: [], cross: [] },
      };
    },
    async validateStrategy(payload) {
      calls.push({ method: 'validateStrategy', args: [payload] });
      return VALIDATION_OK;
    },
    async createStrategy(payload) {
      calls.push({ method: 'createStrategy', args: [payload] });
      return { id: 'strategy-1', versions: [{ id: 'draft-v1', version: 1 }] };
    },
    async finalizeStrategyVersion(strategyId, payload) {
      calls.push({
        method: 'finalizeStrategyVersion',
        args: [strategyId, payload],
      });
      return { id: 'version-1', version: 1, status: 'ready' };
    },
    async runBacktest(payload) {
      calls.push({ method: 'runBacktest', args: [payload] });
      return { id: 'bt-1', status: 'queued' };
    },
    async waitForBacktestCompletion(backtestId) {
      return {
        id: backtestId,
        status: 'completed',
        summaryJson: {
          returnPct: 0.05,
          sharpeRatio: 0.5,
          sortinoRatio: 0.7,
          maxDrawdown: 0.1,
          profitFactor: 1.2,
          totalPositions: 12,
        },
      };
    },
  };
}

describe('runResearchRunner indicator-aware warmup', () => {
  it('auto-bumps warmupPeriod to the longest indicator length when the LLM under-sets it', async () => {
    const client = makeClient();
    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'SMA200 trend strategy.',
        instrument: 'BTCUSDT',
        timeframe: '4h',
        rounds: 1,
      },
      draftProducer: () => makeIndicatorDraft({ warmupPeriod: 50 }),
    });

    assert.equal(result.status, 'completed');
    const finalizeCall = client.calls.find(
      (call) => call.method === 'finalizeStrategyVersion',
    );
    assert.ok(finalizeCall, 'finalize should be called');
    assert.equal(
      finalizeCall.args[1].settings.warmupPeriod,
      200,
      'runner must bump warmupPeriod to match longest indicator length',
    );

    const normalizeLogs = result.rounds[0].logs.filter(
      (log) =>
        log.step === 'normalize' &&
        log.message.includes('warmupPeriod'),
    );
    assert.ok(
      normalizeLogs.length >= 1,
      'a normalize log entry must record the warmup bump',
    );
  });

  it('leaves warmupPeriod alone when it already matches the longest indicator length', async () => {
    const client = makeClient();
    await runResearchRunner({
      client,
      input: {
        prompt: 'SMA200 trend strategy.',
        instrument: 'BTCUSDT',
        timeframe: '4h',
        rounds: 1,
      },
      draftProducer: () => makeIndicatorDraft({ warmupPeriod: 250 }),
    });

    const finalizeCall = client.calls.find(
      (call) => call.method === 'finalizeStrategyVersion',
    );
    assert.equal(finalizeCall.args[1].settings.warmupPeriod, 250);
  });
});

describe('runResearchRunner range pre-resolution', () => {
  it('resolves ISO date strings into epoch ms before persist/backtest', async () => {
    const client = makeClient();
    await runResearchRunner({
      client,
      input: {
        prompt: 'BTC strategy.',
        instrument: 'BTCUSDT',
        timeframe: '4h',
        rounds: 1,
      },
      draftProducer: () =>
        makeIndicatorDraft({
          warmupPeriod: 200,
          rangeStart: '2024-01-01',
          rangeEnd: '2024-12-31',
        }),
    });

    const runBacktestCall = client.calls.find(
      (call) => call.method === 'runBacktest',
    );
    assert.ok(runBacktestCall, 'runBacktest should be called');
    const sentRange = runBacktestCall.args[0].config.range;
    assert.equal(sentRange.start, Date.UTC(2024, 0, 1));
    assert.equal(sentRange.end, Date.UTC(2024, 11, 31));
  });

  it('drops "inception" / "now" symbolic tokens since the API default already covers them', async () => {
    const client = makeClient();
    await runResearchRunner({
      client,
      input: {
        prompt: 'BTC strategy.',
        instrument: 'BTCUSDT',
        timeframe: '4h',
        rounds: 1,
      },
      draftProducer: () =>
        makeIndicatorDraft({
          warmupPeriod: 200,
          rangeStart: 'inception',
          rangeEnd: 'now',
        }),
    });

    const runBacktestCall = client.calls.find(
      (call) => call.method === 'runBacktest',
    );
    assert.ok(runBacktestCall, 'runBacktest should be called');
    const sentRange = runBacktestCall.args[0].config.range;
    // Both endpoints stripped because they were symbolic tokens equivalent
    // to the API defaults — the engine still covers full available history.
    assert.ok(
      sentRange === undefined ||
        (sentRange &&
          !('start' in sentRange) &&
          !('end' in sentRange)),
      'symbolic-only range should be omitted from the persisted backtest config',
    );
  });
});
