import { spawn } from 'node:child_process';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { runResearchRunner, selectChampionRound } from '../dist/index.js';

const VALIDATION_OK = {
  valid: true,
  summary: { errors: 0, warnings: 0 },
  issues: {},
};

const VALIDATION_ERROR = {
  valid: false,
  summary: { errors: 1, warnings: 0 },
  issues: {
    tokens: [
      {
        code: 'missing_entry',
        path: 'signalGraph.strategy.entry',
        message: 'Entry trigger is required.',
        severity: 'error',
      },
    ],
  },
};

function makeDraft(name = 'Agent strategy') {
  return {
    name,
    description: 'Generated by an external agent.',
    signalGraph: {
      protocol: 'traseq.signal-graph',
      version: 2,
      nodes: [],
      strategy: { kind: 'strategy' },
    },
    settings: { positionStyle: 'single', warmupPeriod: 200 },
    backtest: {
      timeframe: '4h',
      signalInstrument: { symbol: 'BTCUSDT' },
      initialBalance: 10_000,
    },
  };
}

function makeClient(options = {}) {
  const calls = [];
  const validationQueue = [...(options.validationQueue ?? [VALIDATION_OK])];
  let finalizeCount = 0;
  let backtestCount = 0;

  const client = {
    calls,
    async getManifest() {
      calls.push({ method: 'getManifest', args: [] });
      return { name: 'Traseq Agent API', version: 'v1' };
    },
    async getWorkspaceContext() {
      calls.push({ method: 'getWorkspaceContext', args: [] });
      return {
        workspace: { id: 'workspace-1', name: 'Research' },
        apiKey: { scopes: ['workspace_read', 'strategies_write'] },
      };
    },
    async getUsage() {
      calls.push({ method: 'getUsage', args: [] });
      return { usage: { backtests: 0 }, limits: { backtests: 100 } };
    },
    async getCapabilities() {
      calls.push({ method: 'getCapabilities', args: [] });
      return {
        protocol: 'traseq.capabilities',
        version: 1,
        subscriptionTier: 'pro',
        limits: { maxEntryConditions: 4 },
        signalGraph: { version: 2, nodes: [], bindings: [] },
        indicators: [],
        operators: { compare: ['gt'], cross: ['cross_up'] },
      };
    },
    async validateStrategy(payload) {
      calls.push({ method: 'validateStrategy', args: [payload] });
      return validationQueue.shift() ?? validationQueue.at(-1) ?? VALIDATION_OK;
    },
    async createStrategy(payload) {
      calls.push({ method: 'createStrategy', args: [payload] });
      return { id: 'strategy-1', versions: [{ id: 'draft-v1', version: 1 }] };
    },
    async createStrategyVersion(strategyId, payload) {
      calls.push({
        method: 'createStrategyVersion',
        args: [strategyId, payload],
      });
      return { id: 'draft-v2', version: 2, status: 'draft' };
    },
    async finalizeStrategyVersion(strategyId, payload) {
      calls.push({
        method: 'finalizeStrategyVersion',
        args: [strategyId, payload],
      });
      finalizeCount += 1;
      return {
        id: `version-${finalizeCount}`,
        version: finalizeCount,
        status: 'ready',
      };
    },
    async runBacktest(payload) {
      calls.push({ method: 'runBacktest', args: [payload] });
      backtestCount += 1;
      return { id: `bt-${backtestCount}`, status: 'queued' };
    },
    async waitForBacktestCompletion(backtestId, options) {
      calls.push({
        method: 'waitForBacktestCompletion',
        args: [backtestId, options],
      });
      return {
        id: backtestId,
        status: 'completed',
        summaryJson: {
          returnPct: backtestId === 'bt-1' ? 0.08 : 0.11,
          sharpeRatio: backtestId === 'bt-1' ? 0.9 : 1.2,
          sortinoRatio: 1,
          maxDrawdown: backtestId === 'bt-1' ? 0.12 : 0.1,
          profitFactor: 1.5,
          totalPositions: backtestId === 'bt-1' ? 18 : 24,
        },
      };
    },
  };

  return client;
}

function methodNames(client) {
  return client.calls.map((call) => call.method);
}

describe('runResearchRunner', () => {
  it('runs one valid draft through validate, create, finalize, backtest, and score', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        instrument: 'BTCUSDT',
        timeframe: '4h',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.schemaVersion, 1);
    assert.equal(result.rounds.length, 1);
    assert.equal(result.championRound, 1);
    assert.equal(result.rounds[0].status, 'completed');
    assert.equal(result.rounds[0].finalizedStrategyVersionId, 'version-1');
    assert.equal(result.rounds[0].backtest.id, 'bt-1');
    assert.equal(typeof result.rounds[0].score.total, 'number');
    assert.deepEqual(methodNames(client), [
      'getManifest',
      'getWorkspaceContext',
      'getUsage',
      'getCapabilities',
      'validateStrategy',
      'createStrategy',
      'finalizeStrategyVersion',
      'runBacktest',
      'waitForBacktestCompletion',
    ]);
  });

  it('stops before writes when validation fails without a repair producer', async () => {
    const client = makeClient({ validationQueue: [VALIDATION_ERROR] });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });

    assert.equal(result.status, 'failed');
    assert.equal(result.stopReason, 'validation_failed');
    assert.equal(result.rounds.length, 1);
    assert.equal(result.rounds[0].status, 'failed');
    assert.equal(result.rounds[0].validation.valid, false);
    assert.equal(result.rounds[0].backtest, undefined);
    assert.deepEqual(methodNames(client), [
      'getManifest',
      'getWorkspaceContext',
      'getUsage',
      'getCapabilities',
      'validateStrategy',
    ]);
  });

  it('repairs validation failures with a bounded repair callback', async () => {
    const client = makeClient({
      validationQueue: [VALIDATION_ERROR, VALIDATION_OK],
    });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft('Broken draft'),
      repairProducer: ({ attempt, draft }) => ({
        ...draft,
        name: `Repaired draft ${attempt}`,
      }),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].validationAttempts, 2);
    assert.equal(result.rounds[0].draft.name, 'Repaired draft 1');
    assert.equal(
      methodNames(client).filter((method) => method === 'validateStrategy')
        .length,
      2,
    );
  });

  it('stops after the repair attempt limit is exhausted', async () => {
    const client = makeClient({
      validationQueue: [
        VALIDATION_ERROR,
        VALIDATION_ERROR,
        VALIDATION_ERROR,
        VALIDATION_ERROR,
        VALIDATION_ERROR,
      ],
    });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft('Broken draft'),
      repairProducer: ({ attempt, draft }) => ({
        ...draft,
        name: `Still broken ${attempt}`,
      }),
    });

    assert.equal(result.status, 'failed');
    assert.equal(result.stopReason, 'validation_failed');
    assert.equal(result.rounds[0].validationAttempts, 5);
    assert.equal(
      methodNames(client).filter((method) => method === 'validateStrategy')
        .length,
      5,
    );
    assert.ok(!methodNames(client).includes('createStrategy'));
  });

  it('runs multiple rounds with createStrategyVersion lineage after the first round', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 2,
      },
      draftProducer: ({ round }) => makeDraft(`Round ${round}`),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds.length, 2);
    assert.equal(result.rounds[0].createdStrategyId, 'strategy-1');
    assert.equal(result.rounds[1].createdStrategyId, 'strategy-1');
    assert.equal(result.rounds[1].forkedFromVersionId, 'version-1');

    const createVersionCall = client.calls.find(
      (call) => call.method === 'createStrategyVersion',
    );
    assert.equal(createVersionCall.args[0], 'strategy-1');
    assert.equal(createVersionCall.args[1].forkedFromVersionId, 'version-1');
    assert.equal(result.championRound, 2);
  });
});

describe('runResearchRunner producer timeout', () => {
  it('aborts a stalled draft producer once producerTimeoutMs elapses', async () => {
    const client = makeClient();

    await assert.rejects(
      runResearchRunner({
        client,
        input: {
          prompt: 'Research a simple BTC trend-following strategy.',
          rounds: 1,
        },
        producerTimeoutMs: 50,
        draftProducer: (_ctx, signal) =>
          new Promise((_resolve, reject) => {
            signal.addEventListener('abort', () =>
              reject(new Error('aborted')),
            );
          }),
      }),
      /did not return within 50ms/,
    );

    assert.ok(!methodNames(client).includes('validateStrategy'));
  });

  it('passes the abort signal to the draft producer for cooperative cancellation', async () => {
    const client = makeClient();
    let receivedSignal;

    await assert.rejects(
      runResearchRunner({
        client,
        input: {
          prompt: 'Research a simple BTC trend-following strategy.',
          rounds: 1,
        },
        producerTimeoutMs: 30,
        draftProducer: (_ctx, signal) => {
          receivedSignal = signal;
          return new Promise(() => {});
        },
      }),
      /did not return within/,
    );

    assert.ok(receivedSignal instanceof AbortSignal);
    assert.equal(receivedSignal.aborted, true);
  });
});

describe('runResearchRunner accumulate settings', () => {
  it('rejects accumulate drafts that omit a triggerMode', async () => {
    const client = makeClient();

    await assert.rejects(
      runResearchRunner({
        client,
        input: {
          prompt: 'Research a simple BTC trend-following strategy.',
          rounds: 1,
        },
        draftProducer: () => ({
          ...makeDraft(),
          settings: { positionStyle: 'accumulate' },
        }),
      }),
      /accumulation block/,
    );
  });

  it('accepts accumulate drafts with a valid triggerMode', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => ({
        ...makeDraft(),
        settings: {
          positionStyle: 'accumulate',
          accumulation: { triggerMode: 'scheduled' },
        },
      }),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].draft.settings.positionStyle, 'accumulate');
  });
});

describe('selectChampionRound', () => {
  it('prefers score, then lower drawdown, then larger sample size', () => {
    const champion = selectChampionRound([
      {
        round: 1,
        status: 'completed',
        score: { total: 10 },
        backtest: { summary: { maxDrawdown: 0.2, totalPositions: 50 } },
      },
      {
        round: 2,
        status: 'completed',
        score: { total: 12 },
        backtest: { summary: { maxDrawdown: 0.5, totalPositions: 5 } },
      },
      {
        round: 3,
        status: 'completed',
        score: { total: 12 },
        backtest: { summary: { maxDrawdown: 0.1, totalPositions: 15 } },
      },
      {
        round: 4,
        status: 'completed',
        score: { total: 12 },
        backtest: { summary: { maxDrawdown: 0.1, totalPositions: 30 } },
      },
      {
        round: 5,
        status: 'failed',
        score: { total: 100 },
        backtest: { summary: { maxDrawdown: 0.01, totalPositions: 100 } },
      },
    ]);

    assert.equal(champion.round, 4);
  });
});

function runCli(args, { env, input } = {}) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, ['dist/cli.js', ...args], {
      cwd: new URL('..', import.meta.url),
      env: { ...process.env, ...env },
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => {
      stdout += chunk;
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk;
    });
    child.on('close', (code) => {
      resolve({ code, stdout, stderr });
    });

    if (input !== undefined) {
      child.stdin.end(input);
    } else {
      child.stdin.end();
    }
  });
}

describe('research-run CLI', () => {
  it('accepts --draft JSON and prints a completed JSON result', async () => {
    const result = await runCli(
      [
        'research-run',
        '--prompt',
        'Research a simple BTC trend-following strategy.',
        '--draft',
        JSON.stringify(makeDraft()),
      ],
      {
        env: {
          NODE_OPTIONS: '--import ./test/mock-cli-fetch.mjs',
          TRASEQ_AGENT_TEST_VALIDATION: 'ok',
          TRASEQ_API_KEY: 'test-key',
          TRASEQ_BASE_URL: 'https://api.test.local',
        },
      },
    );

    assert.equal(result.code, 0, result.stderr);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.status, 'completed');
    assert.equal(parsed.rounds[0].backtest.id, 'bt-1');
  });

  it('rejects the --rounds flag because the CLI is single-round', async () => {
    const result = await runCli(
      [
        'research-run',
        '--prompt',
        'Research a simple BTC trend-following strategy.',
        '--rounds',
        '3',
        '--draft',
        JSON.stringify(makeDraft()),
      ],
      {
        env: {
          NODE_OPTIONS: '--import ./test/mock-cli-fetch.mjs',
          TRASEQ_AGENT_TEST_VALIDATION: 'ok',
          TRASEQ_API_KEY: 'test-key',
          TRASEQ_BASE_URL: 'https://api.test.local',
        },
      },
    );

    assert.notEqual(result.code, 0);
    assert.match(result.stderr, /single-round by design/);
  });

  it('accepts --stdin draft JSON and exits non-zero on validation failure', async () => {
    const result = await runCli(
      [
        'research-run',
        '--prompt',
        'Research a simple BTC trend-following strategy.',
        '--stdin',
      ],
      {
        input: JSON.stringify(makeDraft()),
        env: {
          NODE_OPTIONS: '--import ./test/mock-cli-fetch.mjs',
          TRASEQ_AGENT_TEST_VALIDATION: 'fail',
          TRASEQ_API_KEY: 'test-key',
          TRASEQ_BASE_URL: 'https://api.test.local',
        },
      },
    );

    assert.notEqual(result.code, 0);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.status, 'failed');
    assert.equal(parsed.stopReason, 'validation_failed');
    assert.equal(parsed.rounds[0].validation.valid, false);
  });
});
