import { spawn } from 'node:child_process';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { TraseqApiError } from '@traseq/sdk';
import { runResearchRunner, selectChampionRound } from '../dist/index.js';

const VALIDATION_OK = {
  valid: true,
  summary: { errors: 0, warnings: 0 },
  issues: [],
};

const VALIDATION_ERROR = {
  valid: false,
  summary: { errors: 1, warnings: 0 },
  issues: [
    {
      code: 'missing_entry',
      path: 'signalGraph.strategy.entry',
      field: 'signalGraph',
      message: 'Entry trigger is required.',
      severity: 'error',
    },
  ],
};

function makeDraft(name = 'Agent strategy') {
  return {
    name,
    description: 'Generated by an external agent.',
    signalGraph: {
      protocol: 'traseq.signal-graph',
      version: 2,
      nodes: [{ id: 'entry_signal', kind: 'pattern', name: 'inside_bar' }],
      strategy: {
        kind: 'strategy',
        entry: {
          kind: 'entry',
          trigger: { ref: 'entry_signal' },
          action: {
            side: 'long',
            sizing: { mode: 'percent_equity', value: 10 },
          },
        },
      },
    },
    settings: { positionStyle: 'single', warmupPeriod: 200 },
    backtest: {
      timeframe: '4h',
      signalInstrument: { symbol: 'BTCUSDT' },
      initialBalance: 10_000,
    },
  };
}

function makeClient(options = {}) {
  const calls = [];
  const validationQueue = [...(options.validationQueue ?? [VALIDATION_OK])];
  let finalizeCount = 0;
  let backtestCount = 0;

  const client = {
    calls,
    async getManifest() {
      calls.push({ method: 'getManifest', args: [] });
      return { name: 'Traseq Agent API', version: 'v1' };
    },
    async getWorkspaceContext() {
      calls.push({ method: 'getWorkspaceContext', args: [] });
      return {
        workspace: { id: 'workspace-1', name: 'Research' },
        apiKey: { scopes: ['workspace_read', 'strategies_write'] },
      };
    },
    async getUsage() {
      calls.push({ method: 'getUsage', args: [] });
      return { usage: { backtests: 0 }, limits: { backtests: 100 } };
    },
    async getCapabilities() {
      calls.push({ method: 'getCapabilities', args: [] });
      return {
        protocol: 'traseq.capabilities',
        version: 1,
        subscriptionTier: 'pro',
        limits: { maxEntryConditions: 4 },
        signalGraph: { version: 2, nodes: [], bindings: [] },
        indicators: [],
        operators: { compare: ['gt'], cross: ['cross_up'] },
      };
    },
    async validateStrategy(payload) {
      calls.push({ method: 'validateStrategy', args: [payload] });
      return validationQueue.shift() ?? validationQueue.at(-1) ?? VALIDATION_OK;
    },
    async createStrategy(payload) {
      calls.push({ method: 'createStrategy', args: [payload] });
      return { id: 'strategy-1', versions: [{ id: 'draft-v1', version: 1 }] };
    },
    async createStrategyVersion(strategyId, payload) {
      calls.push({
        method: 'createStrategyVersion',
        args: [strategyId, payload],
      });
      return { id: 'draft-v2', version: 2, status: 'draft' };
    },
    async finalizeStrategyVersion(strategyId, payload) {
      calls.push({
        method: 'finalizeStrategyVersion',
        args: [strategyId, payload],
      });
      finalizeCount += 1;
      return {
        id: `version-${finalizeCount}`,
        version: finalizeCount,
        status: 'ready',
      };
    },
    async runBacktest(payload) {
      calls.push({ method: 'runBacktest', args: [payload] });
      backtestCount += 1;
      return { id: `bt-${backtestCount}`, status: 'queued' };
    },
    async waitForBacktestCompletion(backtestId, options) {
      calls.push({
        method: 'waitForBacktestCompletion',
        args: [backtestId, options],
      });
      return {
        id: backtestId,
        status: 'completed',
        summaryJson: {
          returnPct: backtestId === 'bt-1' ? 0.08 : 0.11,
          sharpeRatio: backtestId === 'bt-1' ? 0.9 : 1.2,
          sortinoRatio: 1,
          maxDrawdown: backtestId === 'bt-1' ? 0.12 : 0.1,
          profitFactor: 1.5,
          totalPositions: backtestId === 'bt-1' ? 18 : 24,
        },
      };
    },
  };

  return client;
}

function methodNames(client) {
  return client.calls.map((call) => call.method);
}

describe('runResearchRunner', () => {
  it('runs one valid draft through validate, create, finalize, backtest, and score', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        instrument: 'BTCUSDT',
        timeframe: '4h',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.schemaVersion, 2);
    assert.equal(result.rounds.length, 1);
    assert.equal(result.championRound, 1);
    assert.equal(result.rounds[0].status, 'completed');
    assert.equal(result.rounds[0].finalizedStrategyVersionId, 'version-1');
    assert.equal(result.rounds[0].backtest.id, 'bt-1');
    assert.equal(typeof result.rounds[0].score.total, 'number');
    assert.deepEqual(methodNames(client), [
      'getManifest',
      'getWorkspaceContext',
      'getUsage',
      'getCapabilities',
      'validateStrategy',
      'createStrategy',
      'finalizeStrategyVersion',
      'runBacktest',
      'waitForBacktestCompletion',
    ]);
    const finalizeCall = client.calls.find(
      (call) => call.method === 'finalizeStrategyVersion',
    );
    assert.equal(finalizeCall.args[1].ignoreWarnings, true);
  });

  it('records finalize warnings while continuing to backtest', async () => {
    const client = makeClient();
    client.finalizeStrategyVersion = async (strategyId, payload) => {
      client.calls.push({
        method: 'finalizeStrategyVersion',
        args: [strategyId, payload],
      });
      return {
        id: 'version-warning',
        version: 1,
        status: 'ready',
        warnings: [
          {
            code: 'WARMUP_TOO_SHORT',
            field: 'settings',
            path: 'settings.warmupPeriod',
            message: 'Warmup is lower than the indicator lookback.',
            severity: 'warning',
            gate: 'finalize',
          },
        ],
      };
    };

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].backtest.id, 'bt-1');
    assert.equal(result.rounds[0].warnings[0].code, 'WARMUP_TOO_SHORT');
    assert.equal(result.warnings[0].gate, 'finalize');
    assert.deepEqual(methodNames(client).slice(-2), [
      'runBacktest',
      'waitForBacktestCompletion',
    ]);
  });

  it('stops before writes when validation fails without a repair producer', async () => {
    const client = makeClient({ validationQueue: [VALIDATION_ERROR] });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });

    assert.equal(result.status, 'failed');
    assert.equal(result.failure.reason, 'validation_failed');
    assert.equal(result.failure.phase, 'validate');
    assert.equal(result.rounds.length, 1);
    assert.equal(result.rounds[0].status, 'failed');
    assert.equal(result.rounds[0].validation.valid, false);
    assert.equal(result.rounds[0].backtest, undefined);
    // P0-A: structured issues must be propagated, not just a flat string.
    assert.ok(
      Array.isArray(result.failure.issues) &&
        result.failure.issues.length === 1,
      'result should expose structured failure issues',
    );
    assert.equal(result.failure.issues[0].code, 'missing_entry');
    assert.equal(result.failure.issues[0].severity, 'error');
    assert.equal(result.failure.issues[0].path, 'signalGraph.strategy.entry');
    assert.deepEqual(
      result.failure.issues,
      result.rounds[0].failure.issues,
    );
    assert.deepEqual(methodNames(client), [
      'getManifest',
      'getWorkspaceContext',
      'getUsage',
      'getCapabilities',
      'validateStrategy',
    ]);
  });

  it('exposes repair attempts with before/after validation snapshots (P2-H)', async () => {
    const client = makeClient({
      validationQueue: [VALIDATION_ERROR, VALIDATION_OK],
    });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft('Broken draft'),
      repairProducer: ({ attempt, draft }) => ({
        ...draft,
        name: `Repaired draft ${attempt}`,
      }),
    });

    assert.equal(result.status, 'completed');
    const round = result.rounds[0];
    assert.ok(
      Array.isArray(round.repairAttempts),
      'completed round must surface repairAttempts',
    );
    assert.equal(round.repairAttempts.length, 1);
    assert.equal(round.repairAttempts[0].attempt, 1);
    assert.equal(round.repairAttempts[0].validationBefore.valid, false);
    assert.equal(round.repairAttempts[0].validationAfter.valid, true);
  });

  it('repairs validation failures with a bounded repair callback', async () => {
    const client = makeClient({
      validationQueue: [VALIDATION_ERROR, VALIDATION_OK],
    });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft('Broken draft'),
      repairProducer: ({ attempt, draft }) => ({
        ...draft,
        name: `Repaired draft ${attempt}`,
      }),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].validationAttempts, 2);
    assert.equal(result.rounds[0].draft.name, 'Repaired draft 1');
    assert.equal(
      methodNames(client).filter((method) => method === 'validateStrategy')
        .length,
      2,
    );
  });

  it('records every repair attempt before/after validation across a multi-step recovery (P3-J)', async () => {
    // P3-J end-to-end safety net: lock down that the agent reports each repair
    // step's transition. This is what gives an LLM the ability to reason
    // "attempt 1 fixed missing_entry but exposed missing_exit, attempt 2 then
    // fixed exits" without re-running validate manually.
    const VALIDATION_ENTRY_FIXED_BUT_EXIT_BAD = {
      valid: false,
      summary: { errors: 1, warnings: 0 },
      issues: [
        {
          code: 'missing_exit',
          path: 'signalGraph.strategy.exits',
          field: 'signalGraph',
          message: 'Exit rules required.',
          severity: 'error',
        },
      ],
    };

    const client = makeClient({
      validationQueue: [
        VALIDATION_ERROR,
        VALIDATION_ENTRY_FIXED_BUT_EXIT_BAD,
        VALIDATION_OK,
      ],
    });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Multi-step repair recovery.',
        rounds: 1,
      },
      draftProducer: () => makeDraft('Initially broken'),
      repairProducer: ({ attempt, draft }) => ({
        ...draft,
        name: `Repair attempt ${attempt}`,
      }),
    });

    assert.equal(result.status, 'completed');
    const repairAttempts = result.rounds[0].repairAttempts ?? [];
    assert.equal(repairAttempts.length, 2, 'must record 2 repair attempts');
    // Attempt 1: started with VALIDATION_ERROR, ended with the entry-fixed-
    // but-exit-bad state — different issue codes prove the runner saw the
    // transition correctly.
    assert.equal(
      repairAttempts[0].validationBefore.issues.signalGraph[0].code,
      'missing_entry',
    );
    assert.equal(
      repairAttempts[0].validationAfter.issues.signalGraph[0].code,
      'missing_exit',
    );
    // Attempt 2: cleared everything.
    assert.equal(
      repairAttempts[1].validationBefore.issues.signalGraph[0].code,
      'missing_exit',
    );
    assert.equal(repairAttempts[1].validationAfter.valid, true);
  });

  it('stops after the repair attempt limit is exhausted', async () => {
    const client = makeClient({
      validationQueue: [
        VALIDATION_ERROR,
        VALIDATION_ERROR,
        VALIDATION_ERROR,
        VALIDATION_ERROR,
        VALIDATION_ERROR,
      ],
    });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft('Broken draft'),
      repairProducer: ({ attempt, draft }) => ({
        ...draft,
        name: `Still broken ${attempt}`,
      }),
    });

    assert.equal(result.status, 'failed');
    assert.equal(result.failure.reason, 'validation_failed');
    assert.equal(result.failure.phase, 'validate');
    assert.equal(result.rounds[0].validationAttempts, 5);
    assert.equal(
      methodNames(client).filter((method) => method === 'validateStrategy')
        .length,
      5,
    );
    assert.ok(!methodNames(client).includes('createStrategy'));
  });

  it('runs multiple rounds with createStrategyVersion lineage after the first round', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 2,
      },
      draftProducer: ({ round }) => makeDraft(`Round ${round}`),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds.length, 2);
    assert.equal(result.rounds[0].createdStrategyId, 'strategy-1');
    assert.equal(result.rounds[1].createdStrategyId, 'strategy-1');
    assert.equal(result.rounds[1].forkedFromVersionId, 'version-1');

    const createVersionCall = client.calls.find(
      (call) => call.method === 'createStrategyVersion',
    );
    assert.equal(createVersionCall.args[0], 'strategy-1');
    assert.equal(createVersionCall.args[1].forkedFromVersionId, 'version-1');
    assert.equal(result.championRound, 2);
  });

  it('versions an existing strategy when strategyId is supplied (no createStrategy call)', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Iterate on an existing BTC trend-following strategy.',
        rounds: 1,
      },
      strategyId: 'strategy-existing',
      draftProducer: () => makeDraft('Iteration'),
    });

    assert.equal(result.status, 'completed');
    assert.ok(
      !methodNames(client).includes('createStrategy'),
      'createStrategy must not be called when strategyId is provided',
    );
    const createVersionCall = client.calls.find(
      (call) => call.method === 'createStrategyVersion',
    );
    assert.ok(createVersionCall, 'createStrategyVersion should be called');
    assert.equal(createVersionCall.args[0], 'strategy-existing');
    assert.equal(
      createVersionCall.args[1].forkedFromVersionId,
      undefined,
      'no forkedFromVersionId when caller did not seed lineage',
    );
    assert.equal(result.rounds[0].createdStrategyId, 'strategy-existing');
    assert.equal(result.rounds[0].forkedFromVersionId, undefined);
  });

  it('threads forkedFromVersionId into round 1 when caller seeds lineage', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Resume iteration from a known finalized version.',
        rounds: 1,
      },
      strategyId: 'strategy-existing',
      forkedFromVersionId: 'version-prior',
      draftProducer: () => makeDraft('Resumed iteration'),
    });

    assert.equal(result.status, 'completed');
    const createVersionCall = client.calls.find(
      (call) => call.method === 'createStrategyVersion',
    );
    assert.ok(createVersionCall, 'createStrategyVersion should be called');
    assert.equal(createVersionCall.args[0], 'strategy-existing');
    assert.equal(
      createVersionCall.args[1].forkedFromVersionId,
      'version-prior',
      'createStrategyVersion payload must carry the seeded lineage',
    );
    assert.equal(result.rounds[0].forkedFromVersionId, 'version-prior');
  });

  it('ignores forkedFromVersionId when strategyId is omitted (brand-new strategy has no parent)', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Author a brand-new strategy.',
        rounds: 1,
      },
      forkedFromVersionId: 'version-prior',
      draftProducer: () => makeDraft('Brand new'),
    });

    assert.equal(result.status, 'completed');
    assert.ok(
      methodNames(client).includes('createStrategy'),
      'createStrategy must run when strategyId is omitted',
    );
    assert.equal(result.rounds[0].forkedFromVersionId, undefined);
  });
});

describe('runResearchRunner producer timeout', () => {
  it('returns producer_timeout failure without throwing when the draft producer stalls', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      producerTimeoutMs: 50,
      draftProducer: (_ctx, signal) =>
        new Promise((_resolve, reject) => {
          signal.addEventListener('abort', () => reject(new Error('aborted')));
        }),
    });

    assert.equal(result.status, 'failed');
    assert.equal(result.failure.reason, 'producer_timeout');
    assert.equal(result.rounds[0].failure.reason, 'producer_timeout');
    assert.match(result.rounds[0].failure.message, /did not return within 50ms/);
    assert.ok(!methodNames(client).includes('validateStrategy'));
  });

  it('passes the abort signal to the draft producer for cooperative cancellation', async () => {
    const client = makeClient();
    let receivedSignal;

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      producerTimeoutMs: 30,
      draftProducer: (_ctx, signal) => {
        receivedSignal = signal;
        return new Promise(() => {});
      },
    });

    assert.equal(result.failure.reason, 'producer_timeout');
    assert.ok(receivedSignal instanceof AbortSignal);
    assert.equal(receivedSignal.aborted, true);
  });
});

describe('runResearchRunner structured failures', () => {
  it('returns producer_error when the draft producer throws', async () => {
    const client = makeClient();
    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => {
        throw new Error('producer crashed');
      },
    });
    assert.equal(result.status, 'failed');
    assert.equal(result.failure.reason, 'producer_error');
    assert.match(result.rounds[0].failure.message, /producer crashed/);
  });

  it('returns create_strategy_failed when createStrategy fails', async () => {
    const client = makeClient();
    client.createStrategy = async () => {
      throw new Error('persistence layer down');
    };
    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });
    assert.equal(result.failure.reason, 'create_strategy_failed');
    assert.equal(result.failure.phase, 'create_strategy');
    assert.match(result.rounds[0].failure.message, /persistence layer down/);
  });

  it('returns backtest_failed when runBacktest fails', async () => {
    const client = makeClient();
    client.runBacktest = async () => {
      throw new Error('backtest queue rejected');
    };
    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });
    assert.equal(result.failure.reason, 'backtest_failed');
    assert.equal(result.failure.phase, 'run_backtest');
  });

  it('returns backtest_timeout when waitForBacktestCompletion times out', async () => {
    const client = makeClient();
    client.waitForBacktestCompletion = async () => {
      throw new Error('Backtest polling timed out after 1000 ms.');
    };
    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });
    assert.equal(result.failure.reason, 'backtest_timeout');
    assert.equal(result.failure.phase, 'wait_backtest');
  });

  it('returns duplicate_version when createStrategyVersion reports duplicate content', async () => {
    const client = makeClient();
    client.createStrategyVersion = async () => {
      throw new TraseqApiError(
        'Duplicate version content',
        409,
        'POST',
        '/public/v1/strategies/strategy-1/versions',
        JSON.stringify({
          message: 'Duplicate version content',
          issues: [
            {
              code: 'DUPLICATE_VERSION',
              field: 'version',
              path: 'version.contentHash',
              severity: 'error',
              message: 'Duplicate version content',
              gate: 'draft_save',
            },
          ],
          existingVersion: {
            id: 'existing-version',
            version: 1,
            status: 'ready',
          },
        }),
      );
    };

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      strategyId: 'strategy-1',
      draftProducer: () => makeDraft(),
    });

    assert.equal(result.failure.reason, 'duplicate_version');
    assert.equal(result.failure.phase, 'create_strategy_version');
    assert.equal(result.failure.issues[0].code, 'DUPLICATE_VERSION');
  });

  it('returns context_failed when the upfront context fetch throws', async () => {
    const client = makeClient();
    client.getCapabilities = async () => {
      throw new Error('capabilities endpoint 503');
    };
    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(),
    });
    assert.equal(result.status, 'failed');
    assert.equal(result.failure.reason, 'context_failed');
    assert.equal(result.failure.phase, 'context');
    assert.equal(result.rounds.length, 0);
  });
});

describe('runResearchRunner accumulate settings', () => {
  it('rejects accumulate drafts that omit a triggerMode', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => ({
        ...makeDraft(),
        settings: { positionStyle: 'accumulate' },
      }),
    });
    assert.equal(result.status, 'failed');
    assert.equal(result.failure.reason, 'producer_error');
    assert.match(result.rounds[0].failure.message, /accumulation block/);
  });

  it('accepts accumulate drafts with a valid triggerMode', async () => {
    const client = makeClient();

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => ({
        ...makeDraft(),
        settings: {
          positionStyle: 'accumulate',
          accumulation: {
            triggerMode: 'scheduled',
            schedule: { cadence: 'weekly', weekday: 1 },
            maxAdds: 12,
          },
        },
      }),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].draft.settings.positionStyle, 'accumulate');
  });

  it('runs the pre-flight cost estimate before runBacktest and attaches it to the round', async () => {
    const client = makeClient();
    client.estimateBacktestCost = async (input) => {
      client.calls.push({ method: 'estimateBacktestCost', args: [input] });
      return {
        estimatedCostUsd: 0.04,
        breakdown: { candleCostUsd: 0.04 },
        estimatedCandleCount: 1000,
        currentBalanceUsd: 1.0,
        afterBalanceUsd: 0.96,
        wouldCauseOverage: false,
        overageAmountUsd: 0,
      };
    };

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => ({
        ...makeDraft(),
        backtest: {
          ...makeDraft().backtest,
          range: { start: 1700000000000, end: 1701000000000 },
        },
      }),
    });

    assert.equal(result.status, 'completed');
    const sequence = methodNames(client);
    assert.ok(
      sequence.indexOf('estimateBacktestCost') >
        sequence.indexOf('finalizeStrategyVersion'),
      'estimate must run after finalize',
    );
    assert.ok(
      sequence.indexOf('estimateBacktestCost') <
        sequence.indexOf('runBacktest'),
      'estimate must run before runBacktest',
    );
    const round = result.rounds[0];
    assert.ok(round.costEstimate, 'costEstimate should be attached');
    assert.equal(round.costEstimate.estimatedCostUsd, 0.04);
    assert.equal(round.costEstimate.wouldCauseOverage, false);
    assert.ok(
      round.logs.some(
        (log) =>
          log.step === 'estimate' &&
          /Pre-flight cost estimate \$/.test(log.message),
      ),
      'log should record the estimate step',
    );
  });

  it('captures wouldCauseOverage and continues to runBacktest (graceful — backend is the gate)', async () => {
    const client = makeClient();
    client.estimateBacktestCost = async () => ({
      estimatedCostUsd: 1.5,
      breakdown: { candleCostUsd: 1.5 },
      estimatedCandleCount: 50000,
      currentBalanceUsd: 0.5,
      afterBalanceUsd: -1.0,
      wouldCauseOverage: true,
      overageAmountUsd: 1.0,
    });

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => ({
        ...makeDraft(),
        backtest: {
          ...makeDraft().backtest,
          range: { start: 1700000000000, end: 1701000000000 },
        },
      }),
    });

    // Round still completes — agent does NOT short-circuit; backend is authoritative.
    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].costEstimate.wouldCauseOverage, true);
    assert.equal(result.rounds[0].costEstimate.overageAmountUsd, 1.0);
    assert.ok(methodNames(client).includes('runBacktest'));
  });

  it('skips the estimate gracefully when the client lacks estimateBacktestCost', async () => {
    const client = makeClient();
    // Default makeClient has no estimateBacktestCost — confirms the runner survives older clients.
    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => ({
        ...makeDraft(),
        backtest: {
          ...makeDraft().backtest,
          range: { start: 1700000000000, end: 1701000000000 },
        },
      }),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].costEstimate, undefined);
    assert.ok(
      result.rounds[0].logs.some(
        (log) => log.step === 'estimate' && /skipped/.test(log.message),
      ),
    );
  });

  it('skips the estimate when the draft has no explicit backtest range', async () => {
    const client = makeClient();
    let estimateCalls = 0;
    client.estimateBacktestCost = async () => {
      estimateCalls += 1;
      return {
        estimatedCostUsd: 0,
        breakdown: {},
        estimatedCandleCount: 0,
        currentBalanceUsd: 1,
        afterBalanceUsd: 1,
        wouldCauseOverage: false,
        overageAmountUsd: 0,
      };
    };

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => makeDraft(), // no range
    });

    assert.equal(result.status, 'completed');
    assert.equal(
      estimateCalls,
      0,
      'estimate should not be called when range is absent',
    );
    assert.equal(result.rounds[0].costEstimate, undefined);
  });

  it('continues with no estimate when estimateBacktestCost throws', async () => {
    const client = makeClient();
    client.estimateBacktestCost = async () => {
      throw new Error('upstream estimate timeout');
    };

    const result = await runResearchRunner({
      client,
      input: {
        prompt: 'Research a simple BTC trend-following strategy.',
        rounds: 1,
      },
      draftProducer: () => ({
        ...makeDraft(),
        backtest: {
          ...makeDraft().backtest,
          range: { start: 1700000000000, end: 1701000000000 },
        },
      }),
    });

    assert.equal(result.status, 'completed');
    assert.equal(result.rounds[0].costEstimate, undefined);
    assert.ok(
      result.rounds[0].logs.some(
        (log) =>
          log.step === 'estimate' &&
          /Pre-flight cost estimate failed/.test(log.message),
      ),
    );
    assert.ok(methodNames(client).includes('runBacktest'));
  });
});

describe('selectChampionRound', () => {
  it('prefers score, then lower drawdown, then larger sample size', () => {
    const champion = selectChampionRound([
      {
        round: 1,
        status: 'completed',
        score: { total: 10 },
        backtest: { summary: { maxDrawdown: 0.2, totalPositions: 50 } },
      },
      {
        round: 2,
        status: 'completed',
        score: { total: 12 },
        backtest: { summary: { maxDrawdown: 0.5, totalPositions: 5 } },
      },
      {
        round: 3,
        status: 'completed',
        score: { total: 12 },
        backtest: { summary: { maxDrawdown: 0.1, totalPositions: 15 } },
      },
      {
        round: 4,
        status: 'completed',
        score: { total: 12 },
        backtest: { summary: { maxDrawdown: 0.1, totalPositions: 30 } },
      },
      {
        round: 5,
        status: 'failed',
        score: { total: 100 },
        backtest: { summary: { maxDrawdown: 0.01, totalPositions: 100 } },
      },
    ]);

    assert.equal(champion.round, 4);
  });
});

function runCli(args, { env, input } = {}) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, ['dist/cli.js', ...args], {
      cwd: new URL('..', import.meta.url),
      env: { ...process.env, ...env },
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => {
      stdout += chunk;
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk;
    });
    child.on('close', (code) => {
      resolve({ code, stdout, stderr });
    });

    if (input !== undefined) {
      child.stdin.end(input);
    } else {
      child.stdin.end();
    }
  });
}

describe('research-run CLI', () => {
  it('accepts --draft JSON and prints a completed JSON result', async () => {
    const result = await runCli(
      [
        'research-run',
        '--prompt',
        'Research a simple BTC trend-following strategy.',
        '--draft',
        JSON.stringify(makeDraft()),
      ],
      {
        env: {
          NODE_OPTIONS: '--import ./test/mock-cli-fetch.mjs',
          TRASEQ_AGENT_TEST_VALIDATION: 'ok',
          TRASEQ_API_KEY: 'test-key',
          TRASEQ_BASE_URL: 'https://api.test.local',
        },
      },
    );

    assert.equal(result.code, 0, result.stderr);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.status, 'completed');
    assert.equal(parsed.rounds[0].backtest.id, 'bt-1');
  });

  it('rejects the --rounds flag because the CLI is single-round', async () => {
    const result = await runCli(
      [
        'research-run',
        '--prompt',
        'Research a simple BTC trend-following strategy.',
        '--rounds',
        '3',
        '--draft',
        JSON.stringify(makeDraft()),
      ],
      {
        env: {
          NODE_OPTIONS: '--import ./test/mock-cli-fetch.mjs',
          TRASEQ_AGENT_TEST_VALIDATION: 'ok',
          TRASEQ_API_KEY: 'test-key',
          TRASEQ_BASE_URL: 'https://api.test.local',
        },
      },
    );

    assert.notEqual(result.code, 0);
    assert.match(result.stderr, /single-round by design/);
  });

  it('accepts --stdin draft JSON and exits non-zero on validation failure', async () => {
    const result = await runCli(
      [
        'research-run',
        '--prompt',
        'Research a simple BTC trend-following strategy.',
        '--stdin',
      ],
      {
        input: JSON.stringify(makeDraft()),
        env: {
          NODE_OPTIONS: '--import ./test/mock-cli-fetch.mjs',
          TRASEQ_AGENT_TEST_VALIDATION: 'fail',
          TRASEQ_API_KEY: 'test-key',
          TRASEQ_BASE_URL: 'https://api.test.local',
        },
      },
    );

    assert.notEqual(result.code, 0);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.status, 'failed');
    assert.equal(parsed.failure.reason, 'validation_failed');
    assert.equal(parsed.rounds[0].validation.valid, false);
  });
});
