import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { OPERATION_REGISTRY } from '../src/generated/operation-registry';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..', '..', '..');

const domainConstants = JSON.parse(
  readFileSync(
    resolve(root, 'docs/public-docs/domain-constants.json'),
    'utf-8',
  ),
);

const constantsOut = resolve(
  __dirname,
  '..',
  'src',
  'generated',
  'constants.ts',
);
const toolSchemaSnapshotOut = resolve(
  root,
  'docs/public-docs/reference/traseq-agent-tool-schema.json',
);

writeFileSync(
  constantsOut,
  [
    '// Auto-generated by scripts/sync-constants.ts — do NOT edit manually.',
    `export const DOMAIN_CONSTANTS = ${JSON.stringify(domainConstants.constants, null, 2)} as const;`,
    '',
  ].join('\n'),
  'utf-8',
);

writeFileSync(
  toolSchemaSnapshotOut,
  `${JSON.stringify(OPERATION_REGISTRY, null, 2)}\n`,
  'utf-8',
);

console.log('Synced constants →', constantsOut);
console.log('Synced tool schema snapshot →', toolSchemaSnapshotOut);
